// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW5RD-qj1mWYn9RJ_DydD-7EMHISogWQI',
    appId: '1:756597073193:web:c73cbe7795f683e2020338',
    messagingSenderId: '756597073193',
    projectId: 'ai-notes-app-758d5',
    authDomain: 'ai-notes-app-758d5.firebaseapp.com',
    storageBucket: 'ai-notes-app-758d5.firebasestorage.app',
    measurementId: 'G-3LHR3G2ZZM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD15SqhxxDfwaXR56SecgNz76Io0AsKbZY',
    appId: '1:756597073193:android:f44c376e932263e0020338',
    messagingSenderId: '756597073193',
    projectId: 'ai-notes-app-758d5',
    storageBucket: 'ai-notes-app-758d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApJ_1pHRHi0l5HZl0Qyb8Ce4uQx0rIGZU',
    appId: '1:756597073193:ios:7377eb8cd193a1ee020338',
    messagingSenderId: '756597073193',
    projectId: 'ai-notes-app-758d5',
    storageBucket: 'ai-notes-app-758d5.firebasestorage.app',
    iosBundleId: 'com.example.aiNotesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApJ_1pHRHi0l5HZl0Qyb8Ce4uQx0rIGZU',
    appId: '1:756597073193:ios:7377eb8cd193a1ee020338',
    messagingSenderId: '756597073193',
    projectId: 'ai-notes-app-758d5',
    storageBucket: 'ai-notes-app-758d5.firebasestorage.app',
    iosBundleId: 'com.example.aiNotesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAW5RD-qj1mWYn9RJ_DydD-7EMHISogWQI',
    appId: '1:756597073193:web:4e6d2e21e1c61a8a020338',
    messagingSenderId: '756597073193',
    projectId: 'ai-notes-app-758d5',
    authDomain: 'ai-notes-app-758d5.firebaseapp.com',
    storageBucket: 'ai-notes-app-758d5.firebasestorage.app',
    measurementId: 'G-EV40T8VD65',
  );
}
